version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: companydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  company-service:
    build: ./CompanyService
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  student-service:
    build: ./StudentService
    ports:
      - "8082:8080"

  auth-service:
    build: ./AuthService
    ports:
      - "8083:8080"

  coordinator-service:
    build: ./CoordinatorService
    ports:
      - "8084:8080"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"

volumes:
  postgres-data:
