server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: company-service
          uri: http://company-service:8081
          predicates:
            - Path=/company/**
          filters:
            - StripPrefix=1
        - id: coordinator-service
          uri: http://coordinator-service:8084
          predicates:
            - Path=/coordinator/**
          filters:
            - StripPrefix=1
        - id: student-service
          uri: http://student-service:8082
          predicates:
            - Path=/student/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/sistema

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
