/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestionproyectosacademicos.presentation;

import com.mycompany.gestionproyectosacademicos.entities.Company;
import com.mycompany.gestionproyectosacademicos.entities.Project;
import com.mycompany.gestionproyectosacademicos.entities.Student;
import com.mycompany.gestionproyectosacademicos.entities.User;
import com.mycompany.gestionproyectosacademicos.services.AuthService;
import com.mycompany.gestionproyectosacademicos.services.CompanyService;
import com.mycompany.gestionproyectosacademicos.services.ProjectService;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ANACONA
 */
public class GUICompany extends javax.swing.JFrame {

    private final Color colorBackSelect = new Color(217, 217, 217); // #D9D9D9
    private final Color colorTxtSelect = new Color(19, 45, 70);    // #132D46
    private final Color colorBackOrigin = new Color(98, 114, 129);      // #627281
    private final Color colorTxtOrigin = new Color(255, 255, 255);     // #FFFFFF
    //private final AuthService authService;
    /**
     * Creates new form GUICompany
     */
    private CardLayout card;
    private CompanyService companyService;
    private Long companyId;
    private ProjectService projectService;

    public GUICompany(CompanyService companyService, ProjectService projectService, String companyIdStr) {
        this.companyService = companyService;
        this.projectService = projectService;
        this.companyId = Long.parseLong(companyIdStr);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDashboard = new javax.swing.JPanel();
        sepUserCoord = new javax.swing.JSeparator();
        lblUser = new javax.swing.JLabel();
        lblEstudiante = new javax.swing.JLabel();
        btnPublish = new javax.swing.JButton();
        btnMyProjects = new javax.swing.JButton();
        btnCloseSessionCompany = new javax.swing.JButton();
        btnProfileCompany = new javax.swing.JButton();
        jPanelChangingPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelNameProject = new javax.swing.JLabel();
        jLabelObjetives = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelBudget = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextDay = new javax.swing.JTextField();
        jLabelSummary = new javax.swing.JLabel();
        jTextSummary = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextDescription = new javax.swing.JTextField();
        jTextObjetives = new javax.swing.JTextField();
        jTextMaxTime = new javax.swing.JTextField();
        jTextBudget = new javax.swing.JTextField();
        btnPublish1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextNameProject = new javax.swing.JTextField();
        jTextMonth = new javax.swing.JTextField();
        jTextYear = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanelDashboard.setBackground(new java.awt.Color(19, 45, 70));
        jPanelDashboard.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2, true));
        jPanelDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        sepUserCoord.setBackground(new java.awt.Color(155, 70, 47));
        sepUserCoord.setForeground(new java.awt.Color(155, 70, 47));

        lblUser.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Usuario");

        lblEstudiante.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        lblEstudiante.setText("Empresa");

        btnPublish.setBackground(new java.awt.Color(98, 114, 129));
        btnPublish.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPublish.setForeground(new java.awt.Color(255, 255, 255));
        btnPublish.setText("Publicar");
        btnPublish.setMaximumSize(new java.awt.Dimension(28, 17));
        btnPublish.setMinimumSize(new java.awt.Dimension(28, 17));
        btnPublish.setPreferredSize(new java.awt.Dimension(28, 17));
        btnPublish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublishActionPerformed(evt);
            }
        });

        btnMyProjects.setBackground(new java.awt.Color(98, 114, 129));
        btnMyProjects.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMyProjects.setForeground(new java.awt.Color(255, 255, 255));
        btnMyProjects.setLabel("Mis Proyectos");
        btnMyProjects.setMaximumSize(new java.awt.Dimension(28, 17));
        btnMyProjects.setMinimumSize(new java.awt.Dimension(28, 17));
        btnMyProjects.setPreferredSize(new java.awt.Dimension(28, 17));

        btnCloseSessionCompany.setBackground(new java.awt.Color(98, 114, 129));
        btnCloseSessionCompany.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCloseSessionCompany.setForeground(new java.awt.Color(255, 255, 255));
        btnCloseSessionCompany.setLabel("Cerrar Sesíon");
        btnCloseSessionCompany.setMaximumSize(new java.awt.Dimension(75, 19));
        btnCloseSessionCompany.setMinimumSize(new java.awt.Dimension(75, 19));
        btnCloseSessionCompany.setPreferredSize(new java.awt.Dimension(75, 19));
        btnCloseSessionCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseSessionCompanyActionPerformed(evt);
            }
        });

        btnProfileCompany.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnProfileCompany.setLabel("Perfil");
        btnProfileCompany.setMaximumSize(new java.awt.Dimension(28, 17));
        btnProfileCompany.setMinimumSize(new java.awt.Dimension(28, 17));
        btnProfileCompany.setPreferredSize(new java.awt.Dimension(28, 17));
        btnProfileCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileCompanyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDashboardLayout = new javax.swing.GroupLayout(jPanelDashboard);
        jPanelDashboard.setLayout(jPanelDashboardLayout);
        jPanelDashboardLayout.setHorizontalGroup(
            jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDashboardLayout.createSequentialGroup()
                .addGroup(jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDashboardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPublish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMyProjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelDashboardLayout.createSequentialGroup()
                        .addGroup(jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDashboardLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(btnCloseSessionCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDashboardLayout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(lblEstudiante))
                            .addGroup(jPanelDashboardLayout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(lblUser))
                            .addGroup(jPanelDashboardLayout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(sepUserCoord, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 154, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelDashboardLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnProfileCompany, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelDashboardLayout.setVerticalGroup(
            jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDashboardLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepUserCoord, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEstudiante)
                .addGap(135, 135, 135)
                .addComponent(btnPublish, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnMyProjects, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btnCloseSessionCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelDashboardLayout.createSequentialGroup()
                    .addGap(176, 176, 176)
                    .addComponent(btnProfileCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(300, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanelDashboard);

        jPanelChangingPanel.setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanelChangingPanel.add(jPanel1, "cardProfile");

        jLabelNameProject.setBackground(new java.awt.Color(19, 45, 70));
        jLabelNameProject.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNameProject.setText("Nombre Proyecto");

        jLabelObjetives.setBackground(new java.awt.Color(19, 45, 70));
        jLabelObjetives.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelObjetives.setText("Objetivos");

        jLabel1.setBackground(new java.awt.Color(19, 45, 70));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Tiempo máximo");

        jLabelBudget.setBackground(new java.awt.Color(19, 45, 70));
        jLabelBudget.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelBudget.setText("Presupuesto");

        jLabel3.setBackground(new java.awt.Color(19, 45, 70));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Fecha: (dd/mm/yyyy)");

        jTextDay.setBackground(new java.awt.Color(204, 204, 204));
        jTextDay.setText("00");

        jLabelSummary.setBackground(new java.awt.Color(19, 45, 70));
        jLabelSummary.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelSummary.setText("Resumen");

        jTextSummary.setBackground(new java.awt.Color(204, 204, 204));
        jTextSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSummaryActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(19, 45, 70));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Descripción de necesidad");

        jTextDescription.setBackground(new java.awt.Color(204, 204, 204));

        jTextObjetives.setBackground(new java.awt.Color(204, 204, 204));

        jTextMaxTime.setBackground(new java.awt.Color(204, 204, 204));
        jTextMaxTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMaxTimeActionPerformed(evt);
            }
        });

        jTextBudget.setBackground(new java.awt.Color(204, 204, 204));
        jTextBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBudgetActionPerformed(evt);
            }
        });

        btnPublish1.setBackground(new java.awt.Color(155, 70, 47));
        btnPublish1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPublish1.setForeground(new java.awt.Color(255, 255, 255));
        btnPublish1.setText("Publicar");
        btnPublish1.setMaximumSize(new java.awt.Dimension(28, 17));
        btnPublish1.setMinimumSize(new java.awt.Dimension(28, 17));
        btnPublish1.setPreferredSize(new java.awt.Dimension(28, 17));
        btnPublish1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublish1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Publicación de Proyectos");

        jTextNameProject.setBackground(new java.awt.Color(204, 204, 204));

        jTextMonth.setBackground(new java.awt.Color(204, 204, 204));
        jTextMonth.setText("00");
        jTextMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMonthActionPerformed(evt);
            }
        });

        jTextYear.setBackground(new java.awt.Color(204, 204, 204));
        jTextYear.setText("0000");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextNameProject, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelObjetives)
                    .addComponent(jLabelNameProject)
                    .addComponent(jTextObjetives, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(jLabelSummary)
                    .addComponent(jTextSummary)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPublish1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBudget)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jTextDay, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextYear))
                        .addComponent(jTextBudget, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                        .addComponent(jTextMaxTime))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(36, 36, 36)
                        .addComponent(jLabelSummary)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelNameProject)
                        .addGap(1, 1, 1)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextNameProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabelObjetives))
                    .addComponent(jTextSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextObjetives, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextMaxTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelBudget)
                        .addGap(18, 18, 18)
                        .addComponent(jTextBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextDescription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnPublish1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jPanelChangingPanel.add(jPanel2, "cardsStatusRequests");
        jPanel2.getAccessibleContext().setAccessibleName("");

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Estado Solicitudes");
        jPanel4.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        jPanelChangingPanel.add(jPanel4, "cardConnection");

        getContentPane().add(jPanelChangingPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseSessionCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseSessionCompanyActionPerformed
        AuthService authService = new AuthService(null); // Crear la instancia del servicio de autenticación
        GUILogin login = new GUILogin(authService); // Pasar la instancia al constructor
        login.setVisible(true); // Mostrar la ventana
        this.dispose();
    }//GEN-LAST:event_btnCloseSessionCompanyActionPerformed

    private void btnProfileCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileCompanyActionPerformed
        card = (CardLayout) this.jPanelChangingPanel.getLayout();
        card.show(jPanelChangingPanel, "cardProfile");
    }//GEN-LAST:event_btnProfileCompanyActionPerformed

    private void btnPublishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublishActionPerformed
        card = (CardLayout) this.jPanelChangingPanel.getLayout();
        card.show(jPanelChangingPanel, "cardsStatusRequests");
    }//GEN-LAST:event_btnPublishActionPerformed

    private void jTextMaxTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMaxTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMaxTimeActionPerformed

    private void jTextBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBudgetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextBudgetActionPerformed

    private void jTextSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSummaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSummaryActionPerformed
    public static LocalDate convertStringToLocalDate(String dateString) {
        // Definir el formato de la fecha
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        try {
            // Convertir String a LocalDate
            return LocalDate.parse(dateString, formatter);
        } catch (DateTimeParseException e) {
            System.out.println("Error al parsear la fecha: " + e.getMessage());
            return null; // Retornar null en caso de error
        }
    }

    public static int convertStringToInt(String numberString) {
        try {
            return Integer.parseInt(numberString); // Intenta convertir el String a int
        } catch (NumberFormatException e) {
            System.out.println("Error: El String no es un número válido. " + e.getMessage());
            return 0; // Retorna 0 o cualquier valor por defecto que desees
        }
    }

    public void validateDate(String date) throws ParseException {
        // Expresión regular para validar el formato dd-MM-yyyy
        String regex = "^(0[1-9]|[12]\\d|3[01])-(0[1-9]|1[0-2])-(\\d{4})$";
        Pattern pattern = Pattern.compile(regex);

        if (!pattern.matcher(date).matches()) {
            throw new ParseException("Formato de fecha incorrecto. Usa dd-MM-yyyy", 0);
        }

        // Verificar si la fecha es válida
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        sdf.setLenient(false); // No permite fechas inválidas como 30-02-2024

        sdf.parse(date); // Si la fecha es inválida, lanzará ParseException
    }


    private void btnPublish1ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String name = jTextNameProject.getText().trim();
            String summary = jTextSummary.getText().trim();
            String goals = jTextObjetives.getText().trim(); // cambia nombre para coincidir con Project
            String description = jTextDescription.getText().trim();
            String maxTime = jTextMaxTime.getText().strip();
            String budgetText = jTextBudget.getText().strip();
            String date = jTextYear.getText().strip() + "-" + jTextMonth.getText().strip() + "-" + jTextDay.getText().strip();
            String status = "Recibido";

            JTextField[] campos = {jTextNameProject, jTextSummary, jTextObjetives, jTextDescription, jTextMaxTime, jTextBudget, jTextDay, jTextMonth, jTextYear};
            String[] valores = {name, summary, goals, description, maxTime, budgetText, jTextDay.getText(), jTextMonth.getText(), jTextYear.getText()};

            boolean hayError = false;

            for (int i = 0; i < campos.length; i++) {
                if (valores[i].isEmpty()) {
                    campos[i].setBackground(Color.RED);
                    hayError = true;
                } else {
                    campos[i].setBackground(Color.LIGHT_GRAY);
                }
            }

            // 6. Mostrar confirmación y limpiar formulario
            JOptionPane.showMessageDialog(this,
                    "Proyecto guardado exitosamente!\n" ,
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);

            int maxTimeValue = Integer.parseInt(maxTime);
            double budgetValue = Double.parseDouble(budgetText);
            if (maxTimeValue <= 0 || budgetValue < 0) {
                throw new IllegalArgumentException("Tiempo máximo debe ser positivo y el presupuesto no negativo.");
            }

            validateDate(date); // Validar formato yyyy-MM-dd
            jTextDay.setBackground(Color.LIGHT_GRAY);

            // Crear el proyecto
            Project project = new Project();
            project.setName(name);
            project.setSummary(summary);
            project.setGoals(goals);
            project.setDescription(description);
            project.setMaxTimeInMonths(maxTimeValue);
            project.setBudget(budgetValue);
            project.setDate(date);
            project.setStatus(status);
            project.setCompanyId(companyId); // Asume que tienes el ID de empresa del usuario logueado

            // Enviar a backend o servicio
            projectService.addProject(project); // Esto debe guardar el proyecto

            JOptionPane.showMessageDialog(this, "Proyecto subido con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El tiempo máximo y el presupuesto deben ser números válidos.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "La fecha debe tener el formato yyyy-MM-dd.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            jTextDay.setBackground(new Color(255, 200, 200));
            jTextMonth.setBackground(new Color(255, 200, 200));
            jTextYear.setBackground(new Color(255, 200, 200));
            throw e;
        }
    }                                           


    private void limpiarFormulario() {
        jTextNameProject.setText("");
        jTextSummary.setText("");
        jTextObjetives.setText("");
        jTextDescription.setText("");
        jTextMaxTime.setText("");
        jTextBudget.setText("");
        jTextDay.setText("dd");
        jTextMonth.setText("mm");
        jTextYear.setText("yyyy");

        // Restaurar colores
        for (JTextField campo : new JTextField[]{jTextNameProject, jTextSummary, jTextObjetives,
                jTextDescription, jTextMaxTime, jTextBudget, jTextDay, jTextMonth, jTextYear}) {
            campo.setBackground(Color.WHITE);
        }
    }
    private void jTextMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMonthActionPerformed

    private void changeColorBtn(JButton botonSeleccionado) {
        // Restaurar el estilo de todos los botones
        for (JButton boton : new JButton[]{btnProfileCompany, btnPublish, btnMyProjects, btnCloseSessionCompany}) {
            boton.setBackground(colorBackOrigin);
            boton.setForeground(colorTxtOrigin);
        }

        // Cambiar el estilo del botón seleccionado
        botonSeleccionado.setBackground(colorBackSelect);
        botonSeleccionado.setForeground(colorTxtSelect);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseSessionCompany;
    private javax.swing.JButton btnMyProjects;
    private javax.swing.JButton btnProfileCompany;
    private javax.swing.JButton btnPublish;
    private javax.swing.JButton btnPublish1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelBudget;
    private javax.swing.JLabel jLabelNameProject;
    private javax.swing.JLabel jLabelObjetives;
    private javax.swing.JLabel jLabelSummary;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelChangingPanel;
    private javax.swing.JPanel jPanelDashboard;
    private javax.swing.JTextField jTextBudget;
    private javax.swing.JTextField jTextDay;
    private javax.swing.JTextField jTextDescription;
    private javax.swing.JTextField jTextMaxTime;
    private javax.swing.JTextField jTextMonth;
    private javax.swing.JTextField jTextNameProject;
    private javax.swing.JTextField jTextObjetives;
    private javax.swing.JTextField jTextSummary;
    private javax.swing.JTextField jTextYear;
    private javax.swing.JLabel lblEstudiante;
    private javax.swing.JLabel lblUser;
    private javax.swing.JSeparator sepUserCoord;
    // End of variables declaration//GEN-END:variables
}
