package com.mycompany.gestionproyectosacademicos.presentation;

import com.mycompany.gestionproyectosacademicos.access.CompanyRepositoryMS;
import com.mycompany.gestionproyectosacademicos.access.ProjectRepositoryMS;
import com.mycompany.gestionproyectosacademicos.access.UserRepositoryMS;
import com.mycompany.gestionproyectosacademicos.entities.Company;
import com.mycompany.gestionproyectosacademicos.entities.Project;
import com.mycompany.gestionproyectosacademicos.observer.IObserver;
import com.mycompany.gestionproyectosacademicos.services.AcademicPeriodGeneratorService;
import com.mycompany.gestionproyectosacademicos.services.ProjectService;
import com.mycompany.gestionproyectosacademicos.services.AuthService;

import com.mycompany.gestionproyectosacademicos.services.CompanyService;
import java.awt.BorderLayout;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.chart.axis.NumberAxis;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridBagConstraints;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.RenderingHints;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;
import javax.swing.border.EmptyBorder;
import javax.swing.table.JTableHeader;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.renderer.category.StandardBarPainter;

public class GUICoordinator extends javax.swing.JFrame implements IObserver {

    // Colores para los gráficos de barras y pastel
    private static final Color[] STATE_COLORS = {
        new Color(19, 45, 70),    // #00039d
        new Color(46, 133, 110),  // #1514b0
        new Color(240, 244, 248),  // #2a24c4
        new Color(255, 126, 103),  // #3e35d7
        new Color(74, 137, 220)   // #5345ea
    };

    private static final String[] STATE_ORDER = {
        "RECEIVED", "IN_PROGRESS", "ACCEPTED", "CLOSED", "REJECTED"
    };
    
    ProjectService projectService = new ProjectService(new ProjectRepositoryMS());
    CompanyService companyService = new CompanyService(new CompanyRepositoryMS());
    private final AcademicPeriodGeneratorService periodGenerator;

    // Colores personalizados
    private final Color colorBackSelect = new Color(217, 217, 217); // #D9D9D9
    private final Color colorTxtSelect = new Color(19, 45, 70);    // #132D46
    private final Color colorBackOrigin = new Color(98, 114, 129);      // #627281
    private final Color colorTxtOrigin = new Color(255, 255, 255);     // #FFFFFF

    /**
     * Creates new form GUIMenu
     */
    public GUICoordinator() {
        this.periodGenerator = new AcademicPeriodGeneratorService();

        this.projectService.addObserver(this);

        initComponents();

        List<String> periods = this.periodGenerator.generateAcademicPeriods();
        for (String period : periods) {
            cmbAcademicPeriod.addItem(period);
            cmbAcademicPeriodStatisticalControl.addItem(period);
        }
        
        // Cargar proyectos inicialmente
        projectService.notifyObservers();
    }

    private void centerContentCells(JTable table) {
        // Crear un renderizador centrado
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER); // Centrar el contenido

        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GUISeeDetails = new javax.swing.JFrame();
        pnlProjectData = new javax.swing.JScrollPane();
        pnl = new javax.swing.JPanel();
        lblProyecto = new javax.swing.JLabel();
        lblProjectName = new javax.swing.JLabel();
        lblGUISummary = new javax.swing.JLabel();
        lblGUIGoals = new javax.swing.JLabel();
        lblGUIDescription = new javax.swing.JLabel();
        lblGUIMaxTimeInMonths = new javax.swing.JLabel();
        lblGUIBudget = new javax.swing.JLabel();
        lblGUIDate = new javax.swing.JLabel();
        btnChangeState = new javax.swing.JButton();
        lblGUIState = new javax.swing.JLabel();
        lblMaxTimeInMonths = new javax.swing.JLabel();
        lblBudget = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblSummary = new javax.swing.JLabel();
        lblGoals = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        pnlCompanyData = new javax.swing.JScrollPane();
        pnlCom = new javax.swing.JPanel();
        lblCompany = new javax.swing.JLabel();
        lblCompanyName = new javax.swing.JLabel();
        lblGUICompanyNit = new javax.swing.JLabel();
        lblGUICompanyEmail = new javax.swing.JLabel();
        lblGUICompanySector = new javax.swing.JLabel();
        lblGUICompanyContactPhone = new javax.swing.JLabel();
        lblGUICompanyContactNames = new javax.swing.JLabel();
        lblGUICompanyContactLastNames = new javax.swing.JLabel();
        lblGUICompanyContactPosition = new javax.swing.JLabel();
        lblCompanyNit = new javax.swing.JLabel();
        lblCompanySector = new javax.swing.JLabel();
        lblCompanyContactPhone = new javax.swing.JLabel();
        lblCompanyContactNames = new javax.swing.JLabel();
        lblCompanyContactLastNames = new javax.swing.JLabel();
        lblCompanyContactPosition = new javax.swing.JLabel();
        lblCompanyEmail = new javax.swing.JLabel();
        GUIComments = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaComments = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        btnComment = new javax.swing.JButton();
        GUIChangeState = new javax.swing.JFrame();
        lblChangeState = new javax.swing.JLabel();
        rBtnApprove = new javax.swing.JRadioButton();
        rBtnAssign = new javax.swing.JRadioButton();
        rBtnComplete = new javax.swing.JRadioButton();
        rBtnPending = new javax.swing.JRadioButton();
        rBtnReject = new javax.swing.JRadioButton();
        btnSaveState = new javax.swing.JToggleButton();
        bgStateOptions = new javax.swing.ButtonGroup();
        jpLeft = new javax.swing.JPanel();
        btnStatisticalControl = new javax.swing.JButton();
        btnRequests = new javax.swing.JButton();
        btnCloseSession = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        sepUserCoord = new javax.swing.JSeparator();
        lblCoordinator = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();
        pnlRequests = new javax.swing.JPanel();
        lblSolicitudes = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequests = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        cmbAcademicPeriod = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        pnlStatisticalControl = new javax.swing.JPanel();
        lblStatisticalControl = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cmbAcademicPeriodStatisticalControl = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();

        GUISeeDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        GUISeeDetails.setResizable(false);
        GUISeeDetails.getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pnlProjectData.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        pnlProjectData.setPreferredSize(new java.awt.Dimension(500, 500));

        pnl.setPreferredSize(pnlProjectData.getPreferredSize());

        lblProyecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblProyecto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProyecto.setText("Proyecto");

        lblProjectName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblProjectName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProjectName.setText("user");

        lblGUISummary.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGUISummary.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGUISummary.setText("Resumen:");

        lblGUIGoals.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGUIGoals.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGUIGoals.setText("Objetivos:");

        lblGUIDescription.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGUIDescription.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGUIDescription.setText("Descripción:");

        lblGUIMaxTimeInMonths.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGUIMaxTimeInMonths.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGUIMaxTimeInMonths.setText("Tiempo máximo en meses: ");

        lblGUIBudget.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGUIBudget.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGUIBudget.setText("Presupuesto: ");

        lblGUIDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGUIDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGUIDate.setText("Fecha:");

        btnChangeState.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnChangeState.setText("Cambiar estado");
        btnChangeState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeStateActionPerformed(evt);
            }
        });

        lblGUIState.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGUIState.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGUIState.setText("Estado:");

        lblMaxTimeInMonths.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaxTimeInMonths.setText("jLabel9");

        lblBudget.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblBudget.setText("jLabel10");

        lblDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDate.setText("jLabel11");

        lblState.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblState.setText("jLabel12");

        lblSummary.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSummary.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSummary.setText("jLabel6");

        lblGoals.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblGoals.setText("jLabel7");

        lblDescription.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDescription.setText("jLabel8");

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5);
        gbc.anchor = GridBagConstraints.WEST;

        javax.swing.GroupLayout pnlLayout = new javax.swing.GroupLayout(pnl);
        pnl.setLayout(pnlLayout);
        pnlLayout.setHorizontalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLayout.createSequentialGroup()
                                        .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblGUIState, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblGUIDate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(23, 23, 23)
                                        .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLayout.createSequentialGroup()
                                        .addComponent(lblGUIBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)
                                        .addComponent(lblBudget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLayout.createSequentialGroup()
                                        .addComponent(lblGUIGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)
                                        .addComponent(lblGoals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLayout.createSequentialGroup()
                                        .addComponent(lblGUISummary, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, Short.MAX_VALUE)
                                        .addComponent(lblSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlLayout.createSequentialGroup()
                                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlLayout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addComponent(lblGUIDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(lblGUIMaxTimeInMonths)
                                        .addGap(18, 18, 18)))
                                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMaxTimeInMonths, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(134, 134, 134))
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(lblProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlLayout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addComponent(lblProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(btnChangeState)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLayout.setVerticalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblProyecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProjectName)
                .addGap(68, 68, 68)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGUISummary)
                    .addComponent(lblSummary))
                .addGap(14, 14, 14)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGUIGoals)
                    .addComponent(lblGoals))
                .addGap(14, 14, 14)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGUIDescription)
                    .addComponent(lblDescription))
                .addGap(18, 18, 18)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGUIMaxTimeInMonths)
                    .addComponent(lblMaxTimeInMonths))
                .addGap(18, 18, 18)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGUIBudget)
                    .addComponent(lblBudget))
                .addGap(14, 14, 14)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGUIDate)
                    .addComponent(lblDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGUIState)
                    .addComponent(lblState))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChangeState)
                .addGap(62, 62, 62))
        );

        pnlProjectData.setViewportView(pnl);

        GUISeeDetails.getContentPane().add(pnlProjectData);

        pnlCompanyData.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        pnlCompanyData.setPreferredSize(new java.awt.Dimension(500, 500));

        pnlCom.setPreferredSize(pnlCompanyData.getPreferredSize());

        lblCompany.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCompany.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompany.setText("Empresa");

        lblCompanyName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCompanyName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompanyName.setText("nombreEmpresa");

        lblGUICompanyNit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGUICompanyNit.setText("Nit:");

        lblGUICompanyEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGUICompanyEmail.setText("Email:");

        lblGUICompanySector.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGUICompanySector.setText("Sector:");

        lblGUICompanyContactPhone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGUICompanyContactPhone.setText("Teléfono de contacto:");

        lblGUICompanyContactNames.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGUICompanyContactNames.setText("Nombres del contacto:");

        lblGUICompanyContactLastNames.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGUICompanyContactLastNames.setText("Apellidos del contacto:");

        lblGUICompanyContactPosition.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGUICompanyContactPosition.setText("Cargo del contacto:");

        lblCompanyNit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCompanyNit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCompanyNit.setText("jLabel6");

        lblCompanySector.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCompanySector.setText("jLabel8");

        lblCompanyContactPhone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCompanyContactPhone.setText("jLabel9");

        lblCompanyContactNames.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCompanyContactNames.setText("jLabel10");

        lblCompanyContactLastNames.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCompanyContactLastNames.setText("jLabel11");

        lblCompanyContactPosition.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCompanyContactPosition.setText("jLabel12");

        lblCompanyEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCompanyEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCompanyEmail.setText("jLabel7");
        lblCompanyEmail.setHorizontalAlignment(JLabel.LEFT); // Alinear a la izquierda
        lblCompanyEmail.setMaximumSize(new Dimension(Integer.MAX_VALUE, lblCompanyEmail.getPreferredSize().height));

        javax.swing.GroupLayout pnlComLayout = new javax.swing.GroupLayout(pnlCom);
        pnlCom.setLayout(pnlComLayout);
        pnlComLayout.setHorizontalGroup(
            pnlComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComLayout.createSequentialGroup()
                .addGroup(pnlComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlComLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(lblCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlComLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(pnlComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlComLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(lblGUICompanySector)
                                .addGap(16, 16, 16)
                                .addComponent(lblCompanySector, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlComLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(lblGUICompanyNit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCompanyNit, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlComLayout.createSequentialGroup()
                                .addComponent(lblGUICompanyContactNames)
                                .addGap(15, 15, 15)
                                .addComponent(lblCompanyContactNames, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlComLayout.createSequentialGroup()
                                .addComponent(lblGUICompanyContactLastNames)
                                .addGap(16, 16, 16)
                                .addComponent(lblCompanyContactLastNames, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlComLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblGUICompanyContactPosition)
                                .addGap(21, 21, 21)
                                .addComponent(lblCompanyContactPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlComLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(lblGUICompanyEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCompanyEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlComLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblGUICompanyContactPhone)
                                .addGap(11, 11, 11)
                                .addComponent(lblCompanyContactPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlComLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(lblCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        pnlComLayout.setVerticalGroup(
            pnlComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblCompany)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCompanyName)
                .addGap(69, 69, 69)
                .addGroup(pnlComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGUICompanyNit)
                    .addComponent(lblCompanyNit))
                .addGap(14, 14, 14)
                .addGroup(pnlComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGUICompanyEmail)
                    .addComponent(lblCompanyEmail))
                .addGap(14, 14, 14)
                .addGroup(pnlComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGUICompanySector)
                    .addComponent(lblCompanySector))
                .addGap(14, 14, 14)
                .addGroup(pnlComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGUICompanyContactPhone)
                    .addComponent(lblCompanyContactPhone))
                .addGap(14, 14, 14)
                .addGroup(pnlComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGUICompanyContactNames)
                    .addComponent(lblCompanyContactNames))
                .addGap(14, 14, 14)
                .addGroup(pnlComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGUICompanyContactLastNames)
                    .addComponent(lblCompanyContactLastNames))
                .addGap(14, 14, 14)
                .addGroup(pnlComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGUICompanyContactPosition)
                    .addComponent(lblCompanyContactPosition))
                .addContainerGap())
        );

        pnlCompanyData.setViewportView(pnlCom);

        GUISeeDetails.getContentPane().add(pnlCompanyData);

        GUISeeDetails.setTitle("Detalles del Proyecto");
        GUISeeDetails.setDefaultCloseOperation(GUISeeDetails.DISPOSE_ON_CLOSE);
        GUISeeDetails.setSize(800, 600); // Tamaño inicial de la ventana
        GUISeeDetails.pack();
        GUISeeDetails.setLocationRelativeTo(null); // Centrar la ventana en la pantalla

        GUIComments.setResizable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Comentarios");

        txtAreaComments.setColumns(20);
        txtAreaComments.setLineWrap(true);
        txtAreaComments.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAreaComments.setWrapStyleWord(true);
        txtAreaComments.setRows(5);
        jScrollPane2.setViewportView(txtAreaComments);

        jLabel7.setText("max. 144 caracteres");

        btnComment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnComment.setText("Comentar");
        btnComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GUICommentsLayout = new javax.swing.GroupLayout(GUIComments.getContentPane());
        GUIComments.getContentPane().setLayout(GUICommentsLayout);
        GUICommentsLayout.setHorizontalGroup(
            GUICommentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUICommentsLayout.createSequentialGroup()
                .addGroup(GUICommentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GUICommentsLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GUICommentsLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(GUICommentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GUICommentsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnComment, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        GUICommentsLayout.setVerticalGroup(
            GUICommentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUICommentsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(btnComment)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        lblChangeState.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblChangeState.setText("Cambiar estado");

        bgStateOptions.add(rBtnApprove);
        rBtnApprove.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rBtnApprove.setText("Aprobado");

        bgStateOptions.add(rBtnAssign);
        rBtnAssign.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rBtnAssign.setText("Asignado");

        bgStateOptions.add(rBtnComplete);
        rBtnComplete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rBtnComplete.setText("Completado");

        bgStateOptions.add(rBtnPending);
        rBtnPending.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rBtnPending.setText("Pendiente");

        bgStateOptions.add(rBtnReject);
        rBtnReject.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rBtnReject.setText("Rechazado");

        btnSaveState.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSaveState.setText("Guardar");
        btnSaveState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveStateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GUIChangeStateLayout = new javax.swing.GroupLayout(GUIChangeState.getContentPane());
        GUIChangeState.getContentPane().setLayout(GUIChangeStateLayout);
        GUIChangeStateLayout.setHorizontalGroup(
            GUIChangeStateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUIChangeStateLayout.createSequentialGroup()
                .addGroup(GUIChangeStateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GUIChangeStateLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblChangeState, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GUIChangeStateLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(GUIChangeStateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rBtnPending)
                            .addGroup(GUIChangeStateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rBtnComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rBtnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rBtnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rBtnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSaveState, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        GUIChangeStateLayout.setVerticalGroup(
            GUIChangeStateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUIChangeStateLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblChangeState)
                .addGap(32, 32, 32)
                .addComponent(rBtnApprove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rBtnAssign)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rBtnComplete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rBtnPending)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rBtnReject)
                .addGap(38, 38, 38)
                .addComponent(btnSaveState)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 540));
        setSize(new java.awt.Dimension(960, 540));

        jpLeft.setBackground(new java.awt.Color(19, 45, 70));
        jpLeft.setAlignmentX(0.0F);
        jpLeft.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnStatisticalControl.setBackground(new java.awt.Color(98, 114, 129));
        btnStatisticalControl.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnStatisticalControl.setForeground(new java.awt.Color(255, 255, 255));
        btnStatisticalControl.setText("Control Estadístico");
        btnStatisticalControl.setBorder(null);
        btnStatisticalControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatisticalControlActionPerformed(evt);
            }
        });

        btnRequests.setBackground(new java.awt.Color(98, 114, 129));
        btnRequests.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnRequests.setForeground(new java.awt.Color(255, 255, 255));
        btnRequests.setText("Solicitudes");
        btnRequests.setBorder(null);
        btnRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestsActionPerformed(evt);
            }
        });

        btnCloseSession.setBackground(new java.awt.Color(98, 114, 129));
        btnCloseSession.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCloseSession.setForeground(new java.awt.Color(255, 255, 255));
        btnCloseSession.setText("Cerrar Sesión");
        btnCloseSession.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCloseSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseSessionActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(19, 45, 70));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUser.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Usuario");
        jPanel1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        sepUserCoord.setBackground(new java.awt.Color(155, 70, 47));
        sepUserCoord.setForeground(new java.awt.Color(155, 70, 47));
        jPanel1.add(sepUserCoord, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 174, 14));

        lblCoordinator.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCoordinator.setForeground(new java.awt.Color(255, 255, 255));
        lblCoordinator.setText("Coordinador");
        jPanel1.add(lblCoordinator, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        javax.swing.GroupLayout jpLeftLayout = new javax.swing.GroupLayout(jpLeft);
        jpLeft.setLayout(jpLeftLayout);
        jpLeftLayout.setHorizontalGroup(
            jpLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnStatisticalControl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRequests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLeftLayout.createSequentialGroup()
                .addGap(6, 96, Short.MAX_VALUE)
                .addComponent(btnCloseSession, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpLeftLayout.setVerticalGroup(
            jpLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLeftLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStatisticalControl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 315, Short.MAX_VALUE)
                .addComponent(btnCloseSession, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        getContentPane().add(jpLeft, java.awt.BorderLayout.LINE_START);

        pnlRight.setBackground(new java.awt.Color(255, 255, 255));
        pnlRight.setLayout(new java.awt.CardLayout());

        pnlRequests.setBackground(new java.awt.Color(255, 255, 255));
        pnlRequests.setLayout(new java.awt.BorderLayout());

        lblSolicitudes.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblSolicitudes.setText("Solicitudes de Proyectos");
        lblSolicitudes.setBorder(new EmptyBorder(70, 50, 20, 20)); // Margen superior, izquierdo, inferior, derecho
        pnlRequests.add(lblSolicitudes, java.awt.BorderLayout.NORTH);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblRequests.setBackground(new java.awt.Color(232, 232, 232));
        tblRequests.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tblRequests.setForeground(new java.awt.Color(40, 40, 40));
        tblRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Empresa", "Proyecto", "Opciones"
            }
        ));
        // Personalizar el contenido de la tabla
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER); // Centrar el contenido

        // Aplicar el renderizador a todas las columnas
        for (int i = 0; i < tblRequests.getColumnCount(); i++) {
            tblRequests.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }

        // Ajustar solo columna "Opciones"
        tblRequests.getColumnModel().getColumn(2).setPreferredWidth(250);

        // Personalizar el encabezado de la tabla
        JTableHeader header = tblRequests.getTableHeader();
        header.setBackground(new Color(157, 157, 157)); // Color de fondo del encabezado
        header.setForeground(new Color(255, 255, 255)); // Color del texto del encabezado
        header.setFont(new Font("Tahoma", Font.BOLD, 24)); // Fuente del encabezado

        // Ajustar la altura del encabezado para que coincida con las filas
        header.setPreferredSize(new Dimension(header.getPreferredSize().width, 80)); // Ancho automático, altura establecida manualmente
        tblRequests.setRowHeight(60);
        tblRequests.setShowHorizontalLines(true);
        tblRequests.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tblRequests);
        centerContentCells(tblRequests);
        jScrollPane1.setBorder(new EmptyBorder(10,50,50,50)); // Margen superior, izquierdo, inferior, derecho
        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(661, 80));

        cmbAcademicPeriod.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbAcademicPeriod.setBorder(null);
        cmbAcademicPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAcademicPeriodActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Periodo Académico:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(314, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addComponent(cmbAcademicPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAcademicPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pnlRequests.add(jPanel4, java.awt.BorderLayout.CENTER);

        pnlRight.add(pnlRequests, "card2");

        pnlStatisticalControl.setBackground(new java.awt.Color(255, 255, 255));
        pnlStatisticalControl.setLayout(new java.awt.BorderLayout());

        lblStatisticalControl.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblStatisticalControl.setText("Estadísticas de proyectos");
        lblStatisticalControl.setBorder(new EmptyBorder(70, 50, 20, 20)); // Margen superior, izquierdo, inferior, derecho
        pnlStatisticalControl.add(lblStatisticalControl, java.awt.BorderLayout.NORTH);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        cmbAcademicPeriodStatisticalControl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbAcademicPeriodStatisticalControl.setBorder(null);
        cmbAcademicPeriodStatisticalControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAcademicPeriodStatisticalControlActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Periodo Académico:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(314, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(28, 28, 28)
                .addComponent(cmbAcademicPeriodStatisticalControl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAcademicPeriodStatisticalControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel6, java.awt.BorderLayout.CENTER);

        pnlStatisticalControl.add(jPanel5, java.awt.BorderLayout.CENTER);

        pnlRight.add(pnlStatisticalControl, "card6");

        getContentPane().add(pnlRight, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseSessionActionPerformed
        AuthService authService = new AuthService(new UserRepositoryMS()); // Crear la instancia del servicio de autenticación
        GUILogin login = new GUILogin(authService); // Pasar la instancia al constructor
        login.setVisible(true); // Mostrar la ventana
        this.dispose();
    }//GEN-LAST:event_btnCloseSessionActionPerformed

    private void btnRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestsActionPerformed
        CardLayout cl = (CardLayout) pnlRight.getLayout();
        cl.show(pnlRight, "card2");
        changeColorBtn(btnRequests);

        // Notificar a los observers para llenar la tabla
        this.projectService.notifyObservers();
    }//GEN-LAST:event_btnRequestsActionPerformed

    private JFreeChart createPieChart(Map<String, Long> data) {
        // Crear dataset para el gráfico de pastel
        DefaultPieDataset dataset = new DefaultPieDataset();

        // Traducir los estados a español para mejor presentación
        Map<String, String> stateTranslations = Map.of(
            "RECEIVED", "Recibidos",
            "IN_PROGRESS", "En progreso",
            "ACCEPTED", "Aceptados",
            "CLOSED", "Cerrados",
            "REJECTED", "Rechazados"
        );

        // Agregar datos al dataset
        data.forEach((state, count) -> {
            String translatedState = stateTranslations.getOrDefault(state, state);
            dataset.setValue(translatedState, count);
        });

        // Crear el gráfico de pastel
        JFreeChart chart = ChartFactory.createPieChart(
            "",  // Título
            dataset,                 // Dataset
            true,                    // Mostrar leyenda
            true,                    // Mostrar tooltips
            false                    // No URLs
        );

        // Personalizar el gráfico
        PiePlot plot = (PiePlot) chart.getPlot();
        plot.setSectionOutlinesVisible(false);
        
        plot.setLabelGenerator(null);

        // Eliminar bordes de las secciones
        plot.setSectionOutlinesVisible(false);
        
        // Configurar el fondo transparente
        plot.setBackgroundPaint(null);          // Fondo del plot transparente
        plot.setOutlineVisible(false);          // Eliminar borde del plot
        chart.setBackgroundPaint(null);         // Fondo del chart transparente
        
        // Agregar márgenes internos al gráfico
        plot.setInteriorGap(0.1); // 10% de espacio alrededor del pastel
        plot.setLabelGap(0.02);   // Espacio entre etiquetas y gráfico
        
        // Asignar colores personalizados
        for (int i = 0; i < STATE_ORDER.length; i++) {
            String translatedState = stateTranslations.get(STATE_ORDER[i]);
            if (dataset.getIndex(translatedState) >= 0) {
                plot.setSectionPaint(translatedState, STATE_COLORS[i]);
            }
        }
        
        return chart;
    }

    private JFreeChart createBarChart(Map<String, Long> data) {
        // Crear dataset para el gráfico de barras
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        // Traducir los estados a español para mejor presentación
        Map<String, String> stateTranslations = Map.of(
            "RECEIVED", "Recibidos",
            "IN_PROGRESS", "En progreso",
            "ACCEPTED", "Aceptados",
            "CLOSED", "Cerrados",
            "REJECTED", "Rechazados"
        );

        // Asegurarse de que todos los estados estén presentes, incluso con valor 0
        for (String state : STATE_ORDER) {
            String translatedState = stateTranslations.get(state);
            long count = data.getOrDefault(state, 0L);
            dataset.addValue(count, "Proyectos", translatedState);
        }

        // Crear el gráfico de barras
        JFreeChart chart = ChartFactory.createBarChart(
            "",  // Título
            "Estado",               // Etiqueta eje X
            "Cantidad",             // Etiqueta eje Y
            dataset                // Dataset
        );

        // Personalizar el gráfico
        CategoryPlot plot = chart.getCategoryPlot();
        BarRenderer renderer = (BarRenderer) plot.getRenderer();

        // Configurar todas las barras con el mismo color (#132d46)
        Color barColor = new Color(25, 70, 127); // Equivalente HEX #132d46
        renderer.setSeriesPaint(0, barColor);   // Todas las series usan el mismo color

        renderer.setBarPainter(new StandardBarPainter());
        
        // Estilo de las barras (sin sombras)
        renderer.setDrawBarOutline(false);
        renderer.setShadowVisible(false); // Deshabilitar sombras
        renderer.setSeriesPaint(0, barColor);

        // Deshabilitar cualquier efecto 3D
        //renderer.setRenderAsPercentages(false);
        renderer.setGradientPaintTransformer(null);
        
        // Espaciado entre barras
        renderer.setItemMargin(0.2);

        // Configurar márgenes en el eje X
        CategoryAxis domainAxis = plot.getDomainAxis();
        domainAxis.setLowerMargin(0.05);
        domainAxis.setUpperMargin(0.05);
        domainAxis.setCategoryMargin(0.15);
        domainAxis.setMaximumCategoryLabelLines(3);

        // Configurar eje Y para mostrar 0 cuando no hay valores
        NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
        rangeAxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());
        rangeAxis.setLowerMargin(0.1);
        rangeAxis.setUpperMargin(0.1);
        rangeAxis.setAutoRangeIncludesZero(true); // Asegurar que el 0 esté incluido

        // Configurar fondo
        plot.setBackgroundPaint(Color.WHITE);
        plot.setRangeGridlinePaint(new Color(100, 100, 100));

        // Configurar fondo del chart
        chart.setBackgroundPaint(Color.WHITE);
        
        // Opcional: Personalizar fuente de las etiquetas
        Font labelFont = new Font("SansSerif", Font.PLAIN, 12);
        domainAxis.setTickLabelFont(labelFont);
        rangeAxis.setTickLabelFont(labelFont);
        
        return chart;
    }
    
    private void btnStatisticalControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatisticalControlActionPerformed
        CardLayout cl = (CardLayout) pnlRight.getLayout();
        cl.show(pnlRight, "card6");
        changeColorBtn(btnStatisticalControl);
        
        // Obtener el período académico seleccionado (o el primero si no hay selección)
        String selectedPeriod = (String) cmbAcademicPeriodStatisticalControl.getSelectedItem();
        if (selectedPeriod == null && cmbAcademicPeriodStatisticalControl.getItemCount() > 0) {
            selectedPeriod = (String) cmbAcademicPeriodStatisticalControl.getItemAt(0);
        }
        
        // Filtrar los proyectos por el período académico seleccionado
        List<Project> filteredProjects = selectedPeriod != null ? 
                projectService.getProjectsByAcademicPeriod(selectedPeriod) : 
                projectService.getProjects();

        // Contar los proyectos por estado
        Map<String, Long> projectCounts = projectService.countProjectsByState(filteredProjects);

        // Actualizar las gráficas
        updateCharts(projectCounts);
    }//GEN-LAST:event_btnStatisticalControlActionPerformed

    private void cmbAcademicPeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAcademicPeriodActionPerformed
//        List<Project> projects = projectService.getProjects();
        String selectedPeriod = (String) cmbAcademicPeriod.getSelectedItem();
        // Filtrar los proyectos por el período académico seleccionado
        List<Project> filteredProjects = projectService.getProjectsByAcademicPeriod(selectedPeriod);

        // Actualizar la tabla con los proyectos filtrados
        update(filteredProjects); // Notificar a los observadores con los proyectos filtrados
    }//GEN-LAST:event_cmbAcademicPeriodActionPerformed

    public List<Project> getProjects() {
        return projectService.getProjects();
    }

    private void btnCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommentActionPerformed

    }//GEN-LAST:event_btnCommentActionPerformed

    private void btnChangeStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeStateActionPerformed
        // Obtener el proyecto seleccionado
        int selectedRow = tblRequests.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Por favor seleccione un proyecto", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Obtener el ID del proyecto seleccionado
        Project selectedProject = projectService.getProjects().get(selectedRow);

        // Mostrar la ventana de cambio de estado
        GUIChangeState.setLocationRelativeTo(null);
        GUIChangeState.pack();
        GUIChangeState.setVisible(true);

        // Configurar el estado actual del proyecto en los radio buttons
        switch (selectedProject.getStatus()) {
            case "APPROVED":
                rBtnApprove.setSelected(true);
                break;
            case "ASSIGNED":
                rBtnAssign.setSelected(true);
                break;
            case "COMPLETED":
                rBtnComplete.setSelected(true);
                break;
            case "PENDING":
                rBtnPending.setSelected(true);
                break;
            case "REJECTED":
                rBtnReject.setSelected(true);
                break;
            default:
                rBtnApprove.setSelected(true);
        }
    }//GEN-LAST:event_btnChangeStateActionPerformed

    private void btnSaveStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveStateActionPerformed
        int selectedRow = tblRequests.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningún proyecto", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Project selectedProject = projectService.getProjects().get(selectedRow);
        String newStatus = "";

        if (rBtnApprove.isSelected()) {
            newStatus = "APPROVED";
        } else if (rBtnAssign.isSelected()) {
            newStatus = "ASSIGNED";
        } else if (rBtnComplete.isSelected()) {
            newStatus = "COMPLETED";
        } else if (rBtnPending.isSelected()) {
            newStatus = "PENDING";
        } else if (rBtnReject.isSelected()) {
            newStatus = "REJECTED";
        }
        System.out.println(newStatus);
        boolean success = projectService.evaluateProject(selectedProject.getId(), newStatus);

        if (success) {
            JOptionPane.showMessageDialog(this, "Estado actualizado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            // Actualizar el estado en la interfaz
            selectedProject.setStatus(newStatus); // Actualizar el objeto local
            lblState.setText(newStatus); // Actualizar la etiqueta

            // Forzar actualización de la tabla
            projectService.notifyObservers();

            GUIChangeState.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar el estado", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveStateActionPerformed

    private void cmbAcademicPeriodStatisticalControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAcademicPeriodStatisticalControlActionPerformed
        // Obtener el período académico seleccionado
        String selectedPeriod = (String) cmbAcademicPeriodStatisticalControl.getSelectedItem();

        // Filtrar los proyectos por el período académico seleccionado
        List<Project> filteredProjects = projectService.getProjectsByAcademicPeriod(selectedPeriod);

        // Contar los proyectos por estado para los proyectos filtrados
        Map<String, Long> projectCounts = projectService.countProjectsByState(filteredProjects);

        // Actualizar las gráficas con los nuevos datos
        updateCharts(projectCounts);
    }//GEN-LAST:event_cmbAcademicPeriodStatisticalControlActionPerformed

    private void changeColorBtn(JButton botonSeleccionado) {
        // Restaurar el estilo de todos los botones
        for (JButton boton : new JButton[]{btnStatisticalControl, btnRequests}) {
            boton.setBackground(colorBackOrigin);
            boton.setForeground(colorTxtOrigin);
        }

        // Cambiar el estilo del botón seleccionado
        botonSeleccionado.setBackground(colorBackSelect);
        botonSeleccionado.setForeground(colorTxtSelect);
    }

    public static void main(String args[]) {
        GUICoordinator inst = new GUICoordinator();
        inst.setExtendedState(JFrame.MAXIMIZED_BOTH);  // Esta línea maximiza la ventana
        inst.setLocationRelativeTo(null);
        inst.setVisible(true);
    }

    public void openSeeDetails(int row) throws SQLException {
        // Obtener el modelo de la tabla
        DefaultTableModel model = (DefaultTableModel) tblRequests.getModel();
        
        // Verificar si la fila es válida
        if (row < 0 || row >= model.getRowCount()) {
            System.out.println("Índice fuera de los límites de la tabla.");
            return;
        }

        // Obtener el ID del proyecto desde la tabla (columna oculta)
        Object idValue = tblRequests.getModel().getValueAt(row, 0); // Obtener como Object

        // Verificar el tipo y convertir
        int projectId;
        if (idValue instanceof Long) {
            projectId = ((Long) idValue).intValue(); // Convertir Long a int
        } else if (idValue instanceof Integer) {
            projectId = (Integer) idValue; // Si ya es Integer, castear directamente
        } else {
            // Manejar el caso si el tipo es inesperado (lanzar excepción o loggear error)
            throw new ClassCastException("El ID del proyecto no es ni Long ni Integer: " + idValue.getClass().getName());
        }
        // Buscar el proyecto por ID en el servicio
        Project project = projectService.getProjectById(projectId);

        if (project == null) {
            System.out.println("No se encontró el proyecto con ID: " + projectId);
            return;
        }

        // Configurar los detalles del proyecto en GUISeeDetails
        lblProjectName.setText("<html>" + project.getName() + "</html>");
        lblSummary.setText("<html>" + project.getSummary() + "</html>");
        lblGoals.setText("<html>" + project.getGoals() + "</html>");
        lblDescription.setText("<html>" + project.getDescription() + "</html>");
        lblMaxTimeInMonths.setText(String.valueOf(project.getMaxtimeMonths()));
        lblBudget.setText(String.valueOf(project.getBudget()));
        lblDate.setText(project.getDate().toString());
        lblState.setText(project.getStatus());

        // Configurar los detalles de la empresa
        
        Company company = companyService.getCompany(project.getCompanyId());
        if (company != null) {
            lblCompanyName.setText("<html>" + company.getName() + "</html>");
            lblCompanyNit.setText(company.getNIT());
            lblCompanyEmail.setText(company.getEmail());
            lblCompanySector.setText(company.getSector());
            lblCompanyContactPhone.setText(company.getContactPhoneNumber());
            lblCompanyContactNames.setText(company.getContactNames());
            lblCompanyContactLastNames.setText(company.getContactLastNames());
            lblCompanyContactPosition.setText(company.getContactPosition());
        } else {
            System.out.println("No hay información de la empresa asociada al proyecto.");
        }
        GUISeeDetails.pack();
        // Mostrar la ventana GUISeeDetails
        GUISeeDetails.setVisible(true);
    }

    void comment(Project project) {
        // Configurar el texto actual del JTextArea con el comentario existente
        txtAreaComments.setText(project.getComments());

        // Mostrar la ventana GUIComments
        GUIComments.pack();
        GUIComments.setVisible(true);

        // Configurar la acción del botón btnComentar para guardar el comentario en el proyecto
        btnComment.addActionListener(e -> {
            String comment = txtAreaComments.getText();
            if (comment.length() > 144) {
                comment = comment.substring(0, 144); // Limitar el comentario a 144 caracteres
            }
            project.setComments(comment); // Guardar el comentario en el proyecto
            GUIComments.dispose(); // Cerrar la ventana de comentarios
        });
    }

    @Override
    public void update(Object o) {
        System.out.println("Actualizando tabla con datos...");
        // Verificar si el objeto notificado es una lista de proyectos
        if (o instanceof List<?>) {
            List<?> projects = (List<?>) o;
            System.out.println("Número de proyectos recibidos: " + projects.size());
            // Crear un modelo de tabla para tblRequests
            //DefaultTableModel model = new DefaultTableModel(new String[]{"Nombre", "Empresa", "Opciones"}, 0);
            DefaultTableModel model = new DefaultTableModel(new String[]{"ID", "Nombre", "Opciones"}, 0)
            {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return column == 2; // Solo la columna de opciones es editable
                }
            };
            
            // Llenar la tabla con los proyectos
            for (Object project : projects) {
                if (project instanceof Project) {
                    Project p = (Project) project;
                    //model.addRow(new Object[]{p.getName(), p.getCompany().getName(), ""});
                    model.addRow(new Object[]{p.getId(), p.getName(), ""});
                }
            }
            
            // Asignar el modelo a la tabla
            tblRequests.setModel(model);
            tblRequests.getColumn("Opciones").setCellRenderer(new GUICoordinatorButtonRenderer());
            tblRequests.getColumn("Opciones").setCellEditor(new GUICoordinatorButtonEditor(new JCheckBox(), this));

            // Ocultar la columna ID
            TableColumn idColumn = tblRequests.getColumn("ID");
            idColumn.setMinWidth(0);
            idColumn.setMaxWidth(0);
            idColumn.setWidth(0);
            idColumn.setPreferredWidth(0);
            
            // Centrar el contenido de las celdas en las columnas
            centerContentCells(tblRequests);
            
            // Forzar actualización visual
            tblRequests.revalidate();
            tblRequests.repaint();
        }
    }
    
    private void updateCharts(Map<String, Long> projectCounts) {
        jPanel6.removeAll();
        jPanel6.setLayout(new BorderLayout());

        // Panel contenedor con mejor espaciado
        JPanel chartsContainer = new JPanel(new GridLayout(1, 2, 30, 30));
        chartsContainer.setBorder(new EmptyBorder(40, 40, 40, 40));
        chartsContainer.setBackground(Color.WHITE);

        // Gráfico de pastel
        JFreeChart pieChart = createPieChart(projectCounts);
        ChartPanel pieChartPanel = new ChartPanel(pieChart);
        pieChartPanel.setPreferredSize(new Dimension(450, 350));
        pieChartPanel.setBackground(Color.WHITE);

        // Gráfico de barras
        JFreeChart barChart = createBarChart(projectCounts);
        ChartPanel barChartPanel = new ChartPanel(barChart) {
            @Override
            public void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, 
                                  RenderingHints.VALUE_ANTIALIAS_OFF);
                super.paintComponent(g2);
            }
        };
        barChartPanel.setPreferredSize(new Dimension(450, 350));
        barChartPanel.setBackground(Color.WHITE);

        chartsContainer.add(pieChartPanel);
        chartsContainer.add(barChartPanel);

        jPanel6.add(chartsContainer, BorderLayout.CENTER);
        jPanel6.revalidate();
        jPanel6.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame GUIChangeState;
    private javax.swing.JFrame GUIComments;
    private javax.swing.JFrame GUISeeDetails;
    private javax.swing.ButtonGroup bgStateOptions;
    private javax.swing.JButton btnChangeState;
    private javax.swing.JButton btnCloseSession;
    private javax.swing.JButton btnComment;
    private javax.swing.JButton btnRequests;
    private javax.swing.JToggleButton btnSaveState;
    private javax.swing.JButton btnStatisticalControl;
    private javax.swing.JComboBox<String> cmbAcademicPeriod;
    private javax.swing.JComboBox<String> cmbAcademicPeriodStatisticalControl;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpLeft;
    private javax.swing.JLabel lblBudget;
    private javax.swing.JLabel lblChangeState;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblCompanyContactLastNames;
    private javax.swing.JLabel lblCompanyContactNames;
    private javax.swing.JLabel lblCompanyContactPhone;
    private javax.swing.JLabel lblCompanyContactPosition;
    private javax.swing.JLabel lblCompanyEmail;
    private javax.swing.JLabel lblCompanyName;
    private javax.swing.JLabel lblCompanyNit;
    private javax.swing.JLabel lblCompanySector;
    private javax.swing.JLabel lblCoordinator;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblGUIBudget;
    private javax.swing.JLabel lblGUICompanyContactLastNames;
    private javax.swing.JLabel lblGUICompanyContactNames;
    private javax.swing.JLabel lblGUICompanyContactPhone;
    private javax.swing.JLabel lblGUICompanyContactPosition;
    private javax.swing.JLabel lblGUICompanyEmail;
    private javax.swing.JLabel lblGUICompanyNit;
    private javax.swing.JLabel lblGUICompanySector;
    private javax.swing.JLabel lblGUIDate;
    private javax.swing.JLabel lblGUIDescription;
    private javax.swing.JLabel lblGUIGoals;
    private javax.swing.JLabel lblGUIMaxTimeInMonths;
    private javax.swing.JLabel lblGUIState;
    private javax.swing.JLabel lblGUISummary;
    private javax.swing.JLabel lblGoals;
    private javax.swing.JLabel lblMaxTimeInMonths;
    private javax.swing.JLabel lblProjectName;
    private javax.swing.JLabel lblProyecto;
    private javax.swing.JLabel lblSolicitudes;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStatisticalControl;
    private javax.swing.JLabel lblSummary;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnl;
    private javax.swing.JPanel pnlCom;
    private javax.swing.JScrollPane pnlCompanyData;
    private javax.swing.JScrollPane pnlProjectData;
    private javax.swing.JPanel pnlRequests;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlStatisticalControl;
    private javax.swing.JRadioButton rBtnApprove;
    private javax.swing.JRadioButton rBtnAssign;
    private javax.swing.JRadioButton rBtnComplete;
    private javax.swing.JRadioButton rBtnPending;
    private javax.swing.JRadioButton rBtnReject;
    private javax.swing.JSeparator sepUserCoord;
    private javax.swing.JTable tblRequests;
    private javax.swing.JTextArea txtAreaComments;
    // End of variables declaration//GEN-END:variables

}
